# Copyright (c) 2025 devgagan : https://github.com/devgaganin.  
# Licensed under the GNU General Public License v3.0.  
# See LICENSE file in the repository root for full license text.

import os
from dotenv import load_dotenv

load_dotenv()

# VPS --- FILL COOKIES 🍪 in """ ... """ 

INST_COOKIES = """
# wtite up here insta cookies
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.instagram.com	TRUE	/	TRUE	1778682836	datr	1TP1Z1rKyyBEBjjqq4pY0cMj
.instagram.com	TRUE	/	TRUE	1775572436	csrftoken	A6IEdgO8hyE-QjmtY8d77Q
.instagram.com	TRUE	/	TRUE	1775658836	ig_did	8CB0E931-1DA0-49CB-BC31-7FC82F73509C
.instagram.com	TRUE	/	TRUE	1744727638	wd	360x668
.instagram.com	TRUE	/	TRUE	1778682838	mid	Z_Uz1QABAAENALLujBEws0ZY_Qtp
.instagram.com	TRUE	/	TRUE	1744727638	dpr	3
"""

YTUB_COOKIES = """
# write here yt cookies
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com	TRUE	/	TRUE	1759674786	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgXQ%3D%3D
.youtube.com	TRUE	/	TRUE	1744124555	GPS	1
.youtube.com	TRUE	/	TRUE	1744209204	YSC	FdMoHJ8AE8A
.youtube.com	TRUE	/	TRUE	1759674786	__Secure-ROLLOUT_TOKEN	CInU2aC-7fj1GhDI2vrK08iMAxihtd3Z08iMAw%3D%3D
.youtube.com	TRUE	/	TRUE	1778682787	PREF	f6=40000000&tz=Asia.Kolkata
.youtube.com	TRUE	/	TRUE	1759674786	VISITOR_INFO1_LIVE	Ymjp4U8nrG0
"""

API_ID = os.getenv("API_ID", "29171167")
API_HASH = os.getenv("API_HASH", "7ea2149629e445936619f06a3c0dc716")
BOT_TOKEN = os.getenv("BOT_TOKEN", "")
MONGO_DB = os.getenv("MONGO_DB", "mongodb+srv://saver:saver@cluster0.ftlr8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
OWNER_ID = list(map(int, os.getenv("OWNER_ID", "7251898668").split())) # list seperated via space
DB_NAME = os.getenv("DB_NAME", "tele")
STRING = os.getenv("STRING", None) # optional
LOG_GROUP = int(os.getenv("LOG_GROUP", "-1002213684702")) # optional with -100
FORCE_SUB = int(os.getenv("FORCE_SUB", "-1002442422204")) # optional with -100
MASTER_KEY = os.getenv("MASTER_KEY", "") # for session encryption
IV_KEY = os.getenv("IV_KEY", "") # for decryption
YT_COOKIES = os.getenv("YT_COOKIES", YTUB_COOKIES)
INSTA_COOKIES = os.getenv("INSTA_COOKIES", INST_COOKIES)
FREEMIUM_LIMIT = int(os.getenv("FREEMIUM_LIMIT", "50"))
PREMIUM_LIMIT = int(os.getenv("PREMIUM_LIMIT", "500"))
